---
#
# Playbook will de-provision all resources in a given cloudformation stack
#
- hosts: localhost
  vars:
    env: development
  vars_files:
    - "secrets/{{ env }}.yml"
  environment:
    AWS_ACCESS_KEY_ID: "{{ aws.access_key }}"
    AWS_SECRET_ACCESS_KEY: "{{ aws.secret_key }}"
    AWS_DEFAULT_REGION: "{{ aws.default_region }}"
  connection: local

  tasks:
  - name: install aws-cli
    homebrew:
      name: awscli
      state: present
  - name: check for AWS connection
    shell: aws s3 ls
    register: aws_result
    failed_when: aws_result.rc != 0

  - name: delete all versions from s3 bucket
    script: scripts/s3_versioned_delete.sh {{ lambda_s3_bucket }}
    register: delete_script_output

  - name: destroy s3 bucket
    s3_bucket:
      name: "{{ lambda_s3_bucket }}"
      state: absent
      force: yes

  - name: tear down cloudformation stack
    cloudformation:
      stack_name: "{{ stack_name }}"
      state: absent
