---
#
# Base SAM (Serverless Application Model) Cloudfront template
#
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Resources:
  #
  # resources are generated programmatially from lambda files in s3 bucket
  #
  simpleRequest:
    Type: AWS::Serverless::Function
    Properties:
      Handler: "simpleRequest.handler"
      Runtime: nodejs6.10
      CodeUri: lambda_functions/simpleRequest/dist/
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: "/simpleRequest"
            Method: get
  superBasic:
    Type: AWS::Serverless::Function
    Properties:
      Handler: "superBasic.handler"
      Runtime: nodejs6.10
      CodeUri: lambda_functions/superBasic/dist/
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: "/superBasic"
            Method: get
  trivia:
    Type: AWS::Serverless::Function
    Properties:
      Handler: "trivia.handler"
      Runtime: nodejs6.10
      CodeUri: lambda_functions/trivia/dist/
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: "/trivia"
            Method: get
