  {{ function }}:
    Type: AWS::Serverless::Function
    Properties:
      Handler: "{{ function }}.handler"
      Runtime: nodejs6.10
{% if local_dev|default(false) %}
      CodeUri: lambda_functions/{{ function }}/dist/
{% else %}
      CodeUri:
        Bucket: !Ref s3Bucket
        Key: "{{ function }}.zip"
{% endif %}
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: "/{{ function }}"
            Method: get
