---
#
# Base SAM (Serverless Application Model) Cloudfront template
#
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Resources:
  #
  # resources are generated programmatically from lambda files in s3 bucket
  #
